/**
 * Seed catalog — line items across the canonical trades.
 *
 * Trade slugs come from `lib/catalog/trades.ts` so adding a new trade
 * doesn't require touching this file's type. Prices are 2025 ballpark
 * US averages and explicitly meant to be edited by each user.
 */

import type { TradeSlug } from "@/lib/catalog/trades"

export type CatalogSeedItem = {
  trade: TradeSlug
  description: string
  unit: string
  unitPrice: number
  kind: "material" | "labor"
}

export const CATALOG_SEED: CatalogSeedItem[] = [
  // ============================================
  // DEMO (50 items)
  // ============================================
  { trade: "demo", description: "Demo crew labor", unit: "hr", unitPrice: 55, kind: "labor" },
  { trade: "demo", description: "Skilled demo / selective demo labor", unit: "hr", unitPrice: 75, kind: "labor" },
  { trade: "demo", description: "Demo cabinetry per linear foot", unit: "lf", unitPrice: 18, kind: "labor" },
  { trade: "demo", description: "Demo countertop per linear foot", unit: "lf", unitPrice: 12, kind: "labor" },
  { trade: "demo", description: "Demo tile floor", unit: "sqft", unitPrice: 4.5, kind: "labor" },
  { trade: "demo", description: "Demo hardwood floor", unit: "sqft", unitPrice: 3.5, kind: "labor" },
  { trade: "demo", description: "Demo carpet & pad", unit: "sqft", unitPrice: 1.25, kind: "labor" },
  { trade: "demo", description: "Demo vinyl plank flooring", unit: "sqft", unitPrice: 1.5, kind: "labor" },
  { trade: "demo", description: "Demo drywall (one side)", unit: "sqft", unitPrice: 1.25, kind: "labor" },
  { trade: "demo", description: "Demo plaster wall", unit: "sqft", unitPrice: 2.75, kind: "labor" },
  { trade: "demo", description: "Demo lath & plaster ceiling", unit: "sqft", unitPrice: 3.5, kind: "labor" },
  { trade: "demo", description: "Demo bathtub & surround", unit: "ea", unitPrice: 250, kind: "labor" },
  { trade: "demo", description: "Demo shower", unit: "ea", unitPrice: 285, kind: "labor" },
  { trade: "demo", description: "Demo toilet", unit: "ea", unitPrice: 75, kind: "labor" },
  { trade: "demo", description: "Demo vanity & sink", unit: "ea", unitPrice: 125, kind: "labor" },
  { trade: "demo", description: "Demo non-load-bearing wall (8ft)", unit: "lf", unitPrice: 35, kind: "labor" },
  { trade: "demo", description: "Demo load-bearing wall", unit: "lf", unitPrice: 95, kind: "labor" },
  { trade: "demo", description: "Demo interior door & jamb", unit: "ea", unitPrice: 65, kind: "labor" },
  { trade: "demo", description: "Demo exterior door & jamb", unit: "ea", unitPrice: 145, kind: "labor" },
  { trade: "demo", description: "Demo window", unit: "ea", unitPrice: 125, kind: "labor" },
  { trade: "demo", description: "Demo trim & baseboard", unit: "lf", unitPrice: 1.75, kind: "labor" },
  { trade: "demo", description: "Demo crown molding", unit: "lf", unitPrice: 2.25, kind: "labor" },
  { trade: "demo", description: "Demo popcorn ceiling", unit: "sqft", unitPrice: 1.75, kind: "labor" },
  { trade: "demo", description: "Demo deck per square foot", unit: "sqft", unitPrice: 3.5, kind: "labor" },
  { trade: "demo", description: "Demo concrete patio", unit: "sqft", unitPrice: 6.5, kind: "labor" },
  { trade: "demo", description: "Dump fee — pickup truck load", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "demo", description: "Dump fee — 10 yd dumpster rental", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "demo", description: "Dump fee — 20 yd dumpster rental", unit: "ea", unitPrice: 575, kind: "material" },
  { trade: "demo", description: "Dump fee — 30 yd dumpster rental", unit: "ea", unitPrice: 725, kind: "material" },
  { trade: "demo", description: "6 mil plastic floor protection", unit: "sqft", unitPrice: 0.35, kind: "material" },
  { trade: "demo", description: "Floor protection paper, ram board", unit: "sqft", unitPrice: 0.55, kind: "material" },
  { trade: "demo", description: "Plastic dust barrier with zipper", unit: "ea", unitPrice: 28, kind: "material" },
  { trade: "demo", description: "Heavy-duty contractor trash bags (50 ct)", unit: "ea", unitPrice: 32, kind: "material" },
  { trade: "demo", description: "Demo respirator filter set", unit: "ea", unitPrice: 18, kind: "material" },
  { trade: "demo", description: "Pry bar / wonder bar", unit: "ea", unitPrice: 24, kind: "material" },
  { trade: "demo", description: "Sawzall blades, 5-pack", unit: "ea", unitPrice: 22, kind: "material" },
  { trade: "demo", description: "Sledgehammer rental, daily", unit: "day", unitPrice: 12, kind: "material" },
  { trade: "demo", description: "Asbestos test sample (lab)", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "demo", description: "Lead paint test kit", unit: "ea", unitPrice: 28, kind: "material" },
  { trade: "demo", description: "Mold remediation labor", unit: "hr", unitPrice: 95, kind: "labor" },
  { trade: "demo", description: "Site prep & layout labor", unit: "hr", unitPrice: 65, kind: "labor" },
  { trade: "demo", description: "Demo cleanup labor", unit: "hr", unitPrice: 45, kind: "labor" },
  { trade: "demo", description: "Concrete saw rental, daily", unit: "day", unitPrice: 95, kind: "material" },
  { trade: "demo", description: "Jackhammer rental, daily", unit: "day", unitPrice: 75, kind: "material" },
  { trade: "demo", description: "Skid steer rental, daily", unit: "day", unitPrice: 350, kind: "material" },
  { trade: "demo", description: "Mini-excavator rental, daily", unit: "day", unitPrice: 295, kind: "material" },
  { trade: "demo", description: "Demo fence per linear foot", unit: "lf", unitPrice: 8, kind: "labor" },
  { trade: "demo", description: "Demo chimney brick (per ft height)", unit: "lf", unitPrice: 85, kind: "labor" },
  { trade: "demo", description: "Demo siding per square", unit: "sqft", unitPrice: 1.5, kind: "labor" },
  { trade: "demo", description: "Demo asphalt roof per square", unit: "sqft", unitPrice: 0.85, kind: "labor" },

  // ============================================
  // FRAMING (50 items)
  // ============================================
  { trade: "framing", description: "Framing carpenter labor", unit: "hr", unitPrice: 75, kind: "labor" },
  { trade: "framing", description: "Framing carpenter helper", unit: "hr", unitPrice: 45, kind: "labor" },
  { trade: "framing", description: "2x4 stud, 8ft, SPF", unit: "ea", unitPrice: 4.85, kind: "material" },
  { trade: "framing", description: "2x4 stud, 92-5/8 in (precut)", unit: "ea", unitPrice: 5.15, kind: "material" },
  { trade: "framing", description: "2x6 stud, 8ft, SPF", unit: "ea", unitPrice: 7.95, kind: "material" },
  { trade: "framing", description: "2x6 stud, 10ft, SPF", unit: "ea", unitPrice: 10.25, kind: "material" },
  { trade: "framing", description: "2x8 lumber, 10ft, SPF", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "framing", description: "2x10 lumber, 10ft, SPF", unit: "ea", unitPrice: 19.25, kind: "material" },
  { trade: "framing", description: "2x12 lumber, 10ft, SPF", unit: "ea", unitPrice: 25.95, kind: "material" },
  { trade: "framing", description: "1x4 furring strip, 8ft", unit: "ea", unitPrice: 3.45, kind: "material" },
  { trade: "framing", description: "LVL beam, 1 3/4 x 9 1/4, per ft", unit: "lf", unitPrice: 14.5, kind: "material" },
  { trade: "framing", description: "LVL beam, 1 3/4 x 11 7/8, per ft", unit: "lf", unitPrice: 18.75, kind: "material" },
  { trade: "framing", description: "Glulam beam, 5 1/8 x 12, per ft", unit: "lf", unitPrice: 28.5, kind: "material" },
  { trade: "framing", description: "I-joist, 11-7/8 in, per ft", unit: "lf", unitPrice: 7.25, kind: "material" },
  { trade: "framing", description: "I-joist, 14 in, per ft", unit: "lf", unitPrice: 9.5, kind: "material" },
  { trade: "framing", description: "Roof truss, 24 ft span (engineered)", unit: "ea", unitPrice: 195, kind: "material" },
  { trade: "framing", description: "Roof truss, 28 ft span", unit: "ea", unitPrice: 245, kind: "material" },
  { trade: "framing", description: "Roof truss, 32 ft span", unit: "ea", unitPrice: 295, kind: "material" },
  { trade: "framing", description: "1/2 in CDX plywood, 4x8 sheet", unit: "ea", unitPrice: 38.5, kind: "material" },
  { trade: "framing", description: "5/8 in CDX plywood, 4x8 sheet", unit: "ea", unitPrice: 46.5, kind: "material" },
  { trade: "framing", description: "3/4 in T&G subfloor, 4x8 sheet", unit: "ea", unitPrice: 58.95, kind: "material" },
  { trade: "framing", description: "7/16 in OSB sheathing, 4x8 sheet", unit: "ea", unitPrice: 24.95, kind: "material" },
  { trade: "framing", description: "1/2 in OSB sheathing, 4x8 sheet", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "framing", description: "ZIP system 1/2 in sheathing, 4x8", unit: "ea", unitPrice: 49.5, kind: "material" },
  { trade: "framing", description: "ZIP tape, 3-3/4 in x 90 ft roll", unit: "ea", unitPrice: 26.5, kind: "material" },
  { trade: "framing", description: "House wrap, 9ft x 100ft roll", unit: "ea", unitPrice: 175, kind: "material" },
  { trade: "framing", description: "Pressure-treated 2x4, 8ft", unit: "ea", unitPrice: 7.5, kind: "material" },
  { trade: "framing", description: "Pressure-treated 2x6, 8ft", unit: "ea", unitPrice: 11.5, kind: "material" },
  { trade: "framing", description: "Pressure-treated 4x4, 8ft (post)", unit: "ea", unitPrice: 18.5, kind: "material" },
  { trade: "framing", description: "Sill seal foam, 50ft roll", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "framing", description: "Sill plate anchor bolt, 1/2 x 10 in", unit: "ea", unitPrice: 4.25, kind: "material" },
  { trade: "framing", description: "Simpson H2.5A hurricane tie", unit: "ea", unitPrice: 0.85, kind: "material" },
  { trade: "framing", description: "Simpson LSTA strap, 12 in", unit: "ea", unitPrice: 4.5, kind: "material" },
  { trade: "framing", description: "Simpson joist hanger, 2x10", unit: "ea", unitPrice: 3.95, kind: "material" },
  { trade: "framing", description: "Simpson post base, 4x4", unit: "ea", unitPrice: 12.5, kind: "material" },
  { trade: "framing", description: "Framing nails, 16d common, 50 lb", unit: "ea", unitPrice: 78, kind: "material" },
  { trade: "framing", description: "Sinker nails, 16d, 50 lb", unit: "ea", unitPrice: 85, kind: "material" },
  { trade: "framing", description: "Joist hanger nails, 1.5 in, 5 lb", unit: "ea", unitPrice: 28, kind: "material" },
  { trade: "framing", description: "GRK structural screw, 4 in, 100 ct", unit: "ea", unitPrice: 38, kind: "material" },
  { trade: "framing", description: "Construction adhesive, 28 oz", unit: "ea", unitPrice: 7.95, kind: "material" },
  { trade: "framing", description: "Frame interior partition wall", unit: "lf", unitPrice: 22, kind: "labor" },
  { trade: "framing", description: "Frame exterior 2x6 wall", unit: "lf", unitPrice: 38, kind: "labor" },
  { trade: "framing", description: "Frame floor (joists & subfloor)", unit: "sqft", unitPrice: 9.5, kind: "labor" },
  { trade: "framing", description: "Frame roof (cut & stack)", unit: "sqft", unitPrice: 12.5, kind: "labor" },
  { trade: "framing", description: "Set roof trusses (per truss)", unit: "ea", unitPrice: 35, kind: "labor" },
  { trade: "framing", description: "Sheathe wall (OSB)", unit: "sqft", unitPrice: 1.65, kind: "labor" },
  { trade: "framing", description: "Sheathe roof", unit: "sqft", unitPrice: 1.85, kind: "labor" },
  { trade: "framing", description: "Install LVL header", unit: "ea", unitPrice: 285, kind: "labor" },
  { trade: "framing", description: "Cut & install rough opening (window)", unit: "ea", unitPrice: 165, kind: "labor" },
  { trade: "framing", description: "Cut & install rough opening (door)", unit: "ea", unitPrice: 145, kind: "labor" },

  // ============================================
  // PLUMBING (50 items)
  // ============================================
  { trade: "plumbing", description: "Licensed plumber labor", unit: "hr", unitPrice: 110, kind: "labor" },
  { trade: "plumbing", description: "Plumber's helper / apprentice", unit: "hr", unitPrice: 55, kind: "labor" },
  { trade: "plumbing", description: "1/2 in PEX, 100 ft red", unit: "ea", unitPrice: 42, kind: "material" },
  { trade: "plumbing", description: "1/2 in PEX, 100 ft blue", unit: "ea", unitPrice: 42, kind: "material" },
  { trade: "plumbing", description: "3/4 in PEX, 100 ft", unit: "ea", unitPrice: 78, kind: "material" },
  { trade: "plumbing", description: "1 in PEX, 100 ft", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "plumbing", description: "PEX crimp ring, 1/2 in (50 ct)", unit: "ea", unitPrice: 12, kind: "material" },
  { trade: "plumbing", description: "PEX elbow fitting, 1/2 in", unit: "ea", unitPrice: 1.85, kind: "material" },
  { trade: "plumbing", description: "PEX tee fitting, 1/2 in", unit: "ea", unitPrice: 2.45, kind: "material" },
  { trade: "plumbing", description: "PEX coupling, 1/2 in", unit: "ea", unitPrice: 1.45, kind: "material" },
  { trade: "plumbing", description: "PEX manifold, 6-port", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "plumbing", description: "Quarter-turn shutoff valve, 1/2 in", unit: "ea", unitPrice: 8.5, kind: "material" },
  { trade: "plumbing", description: "Ball valve, full port, 3/4 in", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "plumbing", description: "1/2 in copper pipe, type L, per ft", unit: "lf", unitPrice: 6.85, kind: "material" },
  { trade: "plumbing", description: "3/4 in copper pipe, type L, per ft", unit: "lf", unitPrice: 9.5, kind: "material" },
  { trade: "plumbing", description: "Copper elbow, 1/2 in sweat", unit: "ea", unitPrice: 2.25, kind: "material" },
  { trade: "plumbing", description: "1.5 in PVC pipe, 10 ft", unit: "ea", unitPrice: 11.5, kind: "material" },
  { trade: "plumbing", description: "2 in PVC pipe, 10 ft", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "plumbing", description: "3 in PVC pipe, 10 ft", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "plumbing", description: "4 in PVC pipe, 10 ft", unit: "ea", unitPrice: 32.5, kind: "material" },
  { trade: "plumbing", description: "PVC elbow, 2 in", unit: "ea", unitPrice: 3.95, kind: "material" },
  { trade: "plumbing", description: "PVC sanitary tee, 3 in", unit: "ea", unitPrice: 8.5, kind: "material" },
  { trade: "plumbing", description: "PVC primer & cement combo", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "plumbing", description: "ABS coupling, 2 in", unit: "ea", unitPrice: 2.85, kind: "material" },
  { trade: "plumbing", description: "Toilet, two-piece elongated", unit: "ea", unitPrice: 245, kind: "material" },
  { trade: "plumbing", description: "Toilet, one-piece elongated", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "plumbing", description: "Toilet — high-end Toto/Kohler", unit: "ea", unitPrice: 875, kind: "material" },
  { trade: "plumbing", description: "Wax ring with horn", unit: "ea", unitPrice: 6.5, kind: "material" },
  { trade: "plumbing", description: "Toilet flange, PVC", unit: "ea", unitPrice: 12.5, kind: "material" },
  { trade: "plumbing", description: "Bathroom faucet, single-handle", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "plumbing", description: "Bathroom faucet, mid-range", unit: "ea", unitPrice: 285, kind: "material" },
  { trade: "plumbing", description: "Kitchen faucet, pull-down", unit: "ea", unitPrice: 245, kind: "material" },
  { trade: "plumbing", description: "Kitchen faucet, premium", unit: "ea", unitPrice: 525, kind: "material" },
  { trade: "plumbing", description: "Vanity sink, drop-in 22 in", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "plumbing", description: "Vanity sink, undermount", unit: "ea", unitPrice: 225, kind: "material" },
  { trade: "plumbing", description: "Kitchen sink, 33 in single bowl", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "plumbing", description: "Kitchen sink, 33 in double bowl", unit: "ea", unitPrice: 545, kind: "material" },
  { trade: "plumbing", description: "Garbage disposal, 1/2 HP", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "plumbing", description: "Garbage disposal, 3/4 HP", unit: "ea", unitPrice: 215, kind: "material" },
  { trade: "plumbing", description: "Tub-shower combo, 60 in alcove", unit: "ea", unitPrice: 595, kind: "material" },
  { trade: "plumbing", description: "Cast iron tub, 60 in", unit: "ea", unitPrice: 1850, kind: "material" },
  { trade: "plumbing", description: "Shower valve trim kit", unit: "ea", unitPrice: 165, kind: "material" },
  { trade: "plumbing", description: "Shower valve rough-in", unit: "ea", unitPrice: 95, kind: "material" },
  { trade: "plumbing", description: "Water heater, 50 gal gas", unit: "ea", unitPrice: 1450, kind: "material" },
  { trade: "plumbing", description: "Water heater, 50 gal electric", unit: "ea", unitPrice: 985, kind: "material" },
  { trade: "plumbing", description: "Tankless water heater, gas", unit: "ea", unitPrice: 2450, kind: "material" },
  { trade: "plumbing", description: "Rough plumbing — bathroom", unit: "ea", unitPrice: 1650, kind: "labor" },
  { trade: "plumbing", description: "Rough plumbing — kitchen", unit: "ea", unitPrice: 950, kind: "labor" },
  { trade: "plumbing", description: "Set & connect toilet", unit: "ea", unitPrice: 185, kind: "labor" },
  { trade: "plumbing", description: "Install vanity & sink (no top)", unit: "ea", unitPrice: 245, kind: "labor" },

  // ============================================
  // ELECTRICAL (50 items)
  // ============================================
  { trade: "electrical", description: "Licensed electrician labor", unit: "hr", unitPrice: 95, kind: "labor" },
  { trade: "electrical", description: "Electrician's helper", unit: "hr", unitPrice: 50, kind: "labor" },
  { trade: "electrical", description: "12-2 NM-B Romex, 250 ft", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "electrical", description: "14-2 NM-B Romex, 250 ft", unit: "ea", unitPrice: 98, kind: "material" },
  { trade: "electrical", description: "12-3 NM-B Romex, 250 ft", unit: "ea", unitPrice: 195, kind: "material" },
  { trade: "electrical", description: "14-3 NM-B Romex, 250 ft", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "electrical", description: "10-2 NM-B Romex, 250 ft", unit: "ea", unitPrice: 215, kind: "material" },
  { trade: "electrical", description: "8-3 NM-B Romex, 125 ft (range)", unit: "ea", unitPrice: 285, kind: "material" },
  { trade: "electrical", description: "6-3 NM-B SE cable, per ft", unit: "lf", unitPrice: 5.85, kind: "material" },
  { trade: "electrical", description: "Outlet, 15A duplex, white", unit: "ea", unitPrice: 1.25, kind: "material" },
  { trade: "electrical", description: "Outlet, 20A duplex, commercial grade", unit: "ea", unitPrice: 4.5, kind: "material" },
  { trade: "electrical", description: "Outlet, GFCI 15A", unit: "ea", unitPrice: 18.5, kind: "material" },
  { trade: "electrical", description: "Outlet, GFCI 20A", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "electrical", description: "Outlet, USB-A/USB-C combo", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "electrical", description: "Outlet, weather-resistant exterior", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "electrical", description: "Switch, single-pole 15A", unit: "ea", unitPrice: 1.45, kind: "material" },
  { trade: "electrical", description: "Switch, 3-way", unit: "ea", unitPrice: 3.85, kind: "material" },
  { trade: "electrical", description: "Switch, 4-way", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "electrical", description: "Dimmer, single-pole LED", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "electrical", description: "Smart dimmer, Caseta", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "electrical", description: "Decora switch plate, 1-gang", unit: "ea", unitPrice: 1.25, kind: "material" },
  { trade: "electrical", description: "Decora switch plate, 2-gang", unit: "ea", unitPrice: 2.25, kind: "material" },
  { trade: "electrical", description: "Old-work box, 1-gang", unit: "ea", unitPrice: 2.85, kind: "material" },
  { trade: "electrical", description: "New-work box, 1-gang", unit: "ea", unitPrice: 1.45, kind: "material" },
  { trade: "electrical", description: "4 in round ceiling box", unit: "ea", unitPrice: 2.85, kind: "material" },
  { trade: "electrical", description: "Ceiling fan rated box", unit: "ea", unitPrice: 6.5, kind: "material" },
  { trade: "electrical", description: "Recessed can light, 6 in LED", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "electrical", description: "Recessed can light, 4 in LED", unit: "ea", unitPrice: 18.5, kind: "material" },
  { trade: "electrical", description: "Surface LED disk light, 6 in", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "electrical", description: "Vanity light fixture, 3-bulb", unit: "ea", unitPrice: 95, kind: "material" },
  { trade: "electrical", description: "Pendant fixture, mid-range", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "electrical", description: "Chandelier, 5-light", unit: "ea", unitPrice: 285, kind: "material" },
  { trade: "electrical", description: "Ceiling fan with light", unit: "ea", unitPrice: 245, kind: "material" },
  { trade: "electrical", description: "Bath exhaust fan, 80 CFM", unit: "ea", unitPrice: 75, kind: "material" },
  { trade: "electrical", description: "Bath exhaust fan, 110 CFM w/ light", unit: "ea", unitPrice: 145, kind: "material" },
  { trade: "electrical", description: "Smoke detector, hardwired", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "electrical", description: "Smoke + CO detector, hardwired", unit: "ea", unitPrice: 48.5, kind: "material" },
  { trade: "electrical", description: "200A main panel, 40-circuit", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "electrical", description: "Subpanel, 100A 20-circuit", unit: "ea", unitPrice: 215, kind: "material" },
  { trade: "electrical", description: "Breaker, 15A single-pole", unit: "ea", unitPrice: 8.5, kind: "material" },
  { trade: "electrical", description: "Breaker, 20A single-pole", unit: "ea", unitPrice: 9.5, kind: "material" },
  { trade: "electrical", description: "Breaker, 30A double-pole", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "electrical", description: "Breaker, 50A double-pole (range)", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "electrical", description: "AFCI breaker, 15A", unit: "ea", unitPrice: 48.5, kind: "material" },
  { trade: "electrical", description: "AFCI/GFCI dual function breaker, 20A", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "electrical", description: "Run new circuit (avg 30 ft)", unit: "ea", unitPrice: 145, kind: "labor" },
  { trade: "electrical", description: "Add outlet (existing wall)", unit: "ea", unitPrice: 165, kind: "labor" },
  { trade: "electrical", description: "Add ceiling light (existing wall)", unit: "ea", unitPrice: 245, kind: "labor" },
  { trade: "electrical", description: "Install recessed can light (existing)", unit: "ea", unitPrice: 145, kind: "labor" },
  { trade: "electrical", description: "Panel upgrade 100A → 200A", unit: "ea", unitPrice: 2850, kind: "labor" },

  // ============================================
  // DRYWALL (50 items)
  // ============================================
  { trade: "drywall", description: "Drywall hanger labor", unit: "hr", unitPrice: 55, kind: "labor" },
  { trade: "drywall", description: "Drywall finisher (taper) labor", unit: "hr", unitPrice: 65, kind: "labor" },
  { trade: "drywall", description: "1/2 in drywall, 4x8 sheet", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "drywall", description: "1/2 in drywall, 4x12 sheet", unit: "ea", unitPrice: 19.5, kind: "material" },
  { trade: "drywall", description: "5/8 in Type X drywall, 4x8 sheet", unit: "ea", unitPrice: 18.5, kind: "material" },
  { trade: "drywall", description: "5/8 in Type X drywall, 4x12 sheet", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "drywall", description: "Moisture-resistant drywall (green), 4x8", unit: "ea", unitPrice: 19.5, kind: "material" },
  { trade: "drywall", description: "Cement board, 1/2 in 3x5", unit: "ea", unitPrice: 16.5, kind: "material" },
  { trade: "drywall", description: "Cement board screws, 1 lb", unit: "ea", unitPrice: 9.5, kind: "material" },
  { trade: "drywall", description: "Drywall screws, 1-1/4 in (1 lb)", unit: "ea", unitPrice: 8.5, kind: "material" },
  { trade: "drywall", description: "Drywall screws, 1-5/8 in (1 lb)", unit: "ea", unitPrice: 9, kind: "material" },
  { trade: "drywall", description: "Drywall screws, 1-1/4 in (5 lb)", unit: "ea", unitPrice: 28, kind: "material" },
  { trade: "drywall", description: "Joint compound, 4.5 gal premixed", unit: "ea", unitPrice: 18.5, kind: "material" },
  { trade: "drywall", description: "Topping compound, 4.5 gal", unit: "ea", unitPrice: 19.5, kind: "material" },
  { trade: "drywall", description: "Setting compound, 18 lb (Easy Sand 90)", unit: "ea", unitPrice: 16.5, kind: "material" },
  { trade: "drywall", description: "Paper joint tape, 250 ft roll", unit: "ea", unitPrice: 4.85, kind: "material" },
  { trade: "drywall", description: "Mesh tape, fiberglass, 300 ft", unit: "ea", unitPrice: 9.5, kind: "material" },
  { trade: "drywall", description: "Outside corner bead, metal 8 ft", unit: "ea", unitPrice: 2.95, kind: "material" },
  { trade: "drywall", description: "Outside corner bead, vinyl 8 ft", unit: "ea", unitPrice: 4.5, kind: "material" },
  { trade: "drywall", description: "Bullnose corner bead, 8 ft", unit: "ea", unitPrice: 6.5, kind: "material" },
  { trade: "drywall", description: "L-bead, 10 ft", unit: "ea", unitPrice: 7.5, kind: "material" },
  { trade: "drywall", description: "Drywall sandpaper, 220 grit (5-pk)", unit: "ea", unitPrice: 6.5, kind: "material" },
  { trade: "drywall", description: "Sanding pole with head", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "drywall", description: "Drywall lift rental, daily", unit: "day", unitPrice: 45, kind: "material" },
  { trade: "drywall", description: "Drywall T-square, 48 in", unit: "ea", unitPrice: 32.5, kind: "material" },
  { trade: "drywall", description: "Hang drywall — wall", unit: "sqft", unitPrice: 0.85, kind: "labor" },
  { trade: "drywall", description: "Hang drywall — ceiling", unit: "sqft", unitPrice: 1.15, kind: "labor" },
  { trade: "drywall", description: "Tape & mud, level 4 finish", unit: "sqft", unitPrice: 1.95, kind: "labor" },
  { trade: "drywall", description: "Tape & mud, level 5 (skim coat)", unit: "sqft", unitPrice: 2.65, kind: "labor" },
  { trade: "drywall", description: "Drywall patch, small (≤6 in)", unit: "ea", unitPrice: 65, kind: "labor" },
  { trade: "drywall", description: "Drywall patch, medium (≤2 sqft)", unit: "ea", unitPrice: 145, kind: "labor" },
  { trade: "drywall", description: "Drywall patch, large (>2 sqft)", unit: "sqft", unitPrice: 18.5, kind: "labor" },
  { trade: "drywall", description: "Skim coat existing wall", unit: "sqft", unitPrice: 2.25, kind: "labor" },
  { trade: "drywall", description: "Texture — orange peel", unit: "sqft", unitPrice: 0.85, kind: "labor" },
  { trade: "drywall", description: "Texture — knockdown", unit: "sqft", unitPrice: 0.95, kind: "labor" },
  { trade: "drywall", description: "Smooth-wall finish (level 5)", unit: "sqft", unitPrice: 2.85, kind: "labor" },
  { trade: "drywall", description: "Hang & finish closet", unit: "ea", unitPrice: 425, kind: "labor" },
  { trade: "drywall", description: "Hang & finish bathroom (avg)", unit: "ea", unitPrice: 950, kind: "labor" },
  { trade: "drywall", description: "Repair water-damaged ceiling, 4x8 patch", unit: "ea", unitPrice: 285, kind: "labor" },
  { trade: "drywall", description: "Sand & prep walls for paint", unit: "sqft", unitPrice: 0.45, kind: "labor" },
  { trade: "drywall", description: "Drywall corner bead protector", unit: "ea", unitPrice: 8.5, kind: "material" },
  { trade: "drywall", description: "Acoustic drywall, 5/8 in QuietRock 4x8", unit: "ea", unitPrice: 78, kind: "material" },
  { trade: "drywall", description: "Mold-resistant drywall, 1/2 in 4x8", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "drywall", description: "Tile backer, 1/2 in HardieBacker 3x5", unit: "ea", unitPrice: 18.5, kind: "material" },
  { trade: "drywall", description: "Schluter Kerdi waterproof board, 4x8", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "drywall", description: "Joint compound, 1 gal premixed", unit: "ea", unitPrice: 9.5, kind: "material" },
  { trade: "drywall", description: "Plaster repair, small", unit: "ea", unitPrice: 95, kind: "labor" },
  { trade: "drywall", description: "Mud taping knife, 6 in", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "drywall", description: "Mud taping knife, 12 in", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "drywall", description: "Drywall mud pan, stainless", unit: "ea", unitPrice: 18.5, kind: "material" },

  // ============================================
  // FINISH (50 items)
  // ============================================
  { trade: "finish", description: "Finish carpenter labor", unit: "hr", unitPrice: 85, kind: "labor" },
  { trade: "painting", description: "Painter labor", unit: "hr", unitPrice: 55, kind: "labor" },
  { trade: "tile", description: "Tile setter labor", unit: "hr", unitPrice: 75, kind: "labor" },
  { trade: "flooring", description: "Hardwood floor installer labor", unit: "hr", unitPrice: 65, kind: "labor" },
  { trade: "flooring", description: "Carpet installer labor", unit: "sqft", unitPrice: 0.85, kind: "labor" },
  { trade: "finish", description: "Interior door, hollow-core 30 in pre-hung", unit: "ea", unitPrice: 95, kind: "material" },
  { trade: "finish", description: "Interior door, solid-core 30 in pre-hung", unit: "ea", unitPrice: 195, kind: "material" },
  { trade: "finish", description: "Interior door, panel solid 36 in pre-hung", unit: "ea", unitPrice: 285, kind: "material" },
  { trade: "finish", description: "Exterior door, fiberglass 36 in", unit: "ea", unitPrice: 525, kind: "material" },
  { trade: "finish", description: "Exterior door, steel 36 in", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "finish", description: "French door pair, interior", unit: "ea", unitPrice: 685, kind: "material" },
  { trade: "finish", description: "Pocket door kit + door", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "finish", description: "Door knob set, passage", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "finish", description: "Door knob set, privacy", unit: "ea", unitPrice: 32.5, kind: "material" },
  { trade: "finish", description: "Lever set, mid-range", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "finish", description: "Deadbolt, single-cylinder", unit: "ea", unitPrice: 38.5, kind: "material" },
  { trade: "finish", description: "Window, 36x60 vinyl double-hung", unit: "ea", unitPrice: 425, kind: "material" },
  { trade: "finish", description: "Window, 36x60 wood-clad", unit: "ea", unitPrice: 985, kind: "material" },
  { trade: "finish", description: "Baseboard, 1x6 primed pine, per ft", unit: "lf", unitPrice: 2.85, kind: "material" },
  { trade: "finish", description: "Baseboard, 1x4 primed MDF, per ft", unit: "lf", unitPrice: 1.65, kind: "material" },
  { trade: "finish", description: "Crown molding, 4-1/4 in primed, per ft", unit: "lf", unitPrice: 3.85, kind: "material" },
  { trade: "finish", description: "Crown molding, 5-1/4 in primed, per ft", unit: "lf", unitPrice: 4.65, kind: "material" },
  { trade: "finish", description: "Casing, 2-1/4 in primed, per ft", unit: "lf", unitPrice: 1.95, kind: "material" },
  { trade: "finish", description: "Quarter round, 11/16 in, per ft", unit: "lf", unitPrice: 0.85, kind: "material" },
  { trade: "finish", description: "Wainscot panel, 4x8 beadboard", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "finish", description: "Stain-grade oak baseboard, 1x6, per ft", unit: "lf", unitPrice: 6.85, kind: "material" },
  { trade: "finish", description: "Install baseboard", unit: "lf", unitPrice: 3.5, kind: "labor" },
  { trade: "finish", description: "Install crown molding", unit: "lf", unitPrice: 5.5, kind: "labor" },
  { trade: "finish", description: "Install door & casing", unit: "ea", unitPrice: 245, kind: "labor" },
  { trade: "finish", description: "Install pre-hung interior door", unit: "ea", unitPrice: 165, kind: "labor" },
  { trade: "finish", description: "Hang interior door (only)", unit: "ea", unitPrice: 95, kind: "labor" },
  { trade: "painting", description: "Paint, premium interior, 1 gal", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "painting", description: "Paint, mid-range interior, 1 gal", unit: "ea", unitPrice: 38.5, kind: "material" },
  { trade: "painting", description: "Primer, 1 gal", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "painting", description: "Painter's tape, 1.88 in x 60 yd", unit: "ea", unitPrice: 9.5, kind: "material" },
  { trade: "painting", description: "Drop cloth, 9x12 canvas", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "painting", description: "Roller cover, 9 in (3-pk)", unit: "ea", unitPrice: 14.5, kind: "material" },
  { trade: "painting", description: "Paint walls — 2 coats + primer", unit: "sqft", unitPrice: 1.85, kind: "labor" },
  { trade: "painting", description: "Paint ceiling — flat white", unit: "sqft", unitPrice: 1.25, kind: "labor" },
  { trade: "painting", description: "Paint trim & doors", unit: "lf", unitPrice: 2.5, kind: "labor" },
  { trade: "tile", description: "Tile, 12x24 porcelain, per sqft", unit: "sqft", unitPrice: 4.85, kind: "material" },
  { trade: "tile", description: "Tile, subway 3x6 ceramic, per sqft", unit: "sqft", unitPrice: 4.5, kind: "material" },
  { trade: "tile", description: "Tile, premium porcelain, per sqft", unit: "sqft", unitPrice: 9.85, kind: "material" },
  { trade: "tile", description: "Thinset mortar, 50 lb", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "tile", description: "Grout, sanded 25 lb", unit: "ea", unitPrice: 24.5, kind: "material" },
  { trade: "tile", description: "Tile spacers, 1/8 in (200 ct)", unit: "ea", unitPrice: 6.5, kind: "material" },
  { trade: "tile", description: "Set wall tile", unit: "sqft", unitPrice: 11.5, kind: "labor" },
  { trade: "tile", description: "Set floor tile", unit: "sqft", unitPrice: 9.85, kind: "labor" },
  { trade: "flooring", description: "Hardwood floor, 3/4 in oak, per sqft", unit: "sqft", unitPrice: 6.85, kind: "material" },
  { trade: "flooring", description: "Install hardwood flooring", unit: "sqft", unitPrice: 4.85, kind: "labor" },
  { trade: "flooring", description: "Luxury vinyl plank, per sqft", unit: "sqft", unitPrice: 3.85, kind: "material" },
  { trade: "flooring", description: "Install LVP flooring", unit: "sqft", unitPrice: 2.5, kind: "labor" },
  { trade: "flooring", description: "Carpet, mid-grade nylon, per sqyd", unit: "sqyd", unitPrice: 24.5, kind: "material" },
  { trade: "flooring", description: "Carpet pad, 8 lb rebond, per sqyd", unit: "sqyd", unitPrice: 4.5, kind: "material" },
  { trade: "flooring", description: "Underlayment, 1/4 in plywood, per sheet", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "flooring", description: "Floor leveling compound, 50 lb", unit: "ea", unitPrice: 38.5, kind: "material" },
  { trade: "flooring", description: "Transition strip, T-mold per ft", unit: "lf", unitPrice: 8.5, kind: "material" },
  { trade: "flooring", description: "Refinish hardwood — sand, stain, 3 coats", unit: "sqft", unitPrice: 4.5, kind: "labor" },

  // ============================================
  // HVAC (12 items)
  // ============================================
  { trade: "hvac", description: "HVAC tech labor", unit: "hr", unitPrice: 95, kind: "labor" },
  { trade: "hvac", description: "Furnace, 80% gas 80kBTU", unit: "ea", unitPrice: 1850, kind: "material" },
  { trade: "hvac", description: "Furnace, 96% high-eff gas 80kBTU", unit: "ea", unitPrice: 2850, kind: "material" },
  { trade: "hvac", description: "AC condenser, 2.5 ton 14 SEER", unit: "ea", unitPrice: 1650, kind: "material" },
  { trade: "hvac", description: "AC condenser, 3 ton 16 SEER", unit: "ea", unitPrice: 2250, kind: "material" },
  { trade: "hvac", description: "Mini-split head, 12k BTU", unit: "ea", unitPrice: 685, kind: "material" },
  { trade: "hvac", description: "Mini-split outdoor unit, 24k BTU", unit: "ea", unitPrice: 1485, kind: "material" },
  { trade: "hvac", description: "Smart thermostat (Nest/ecobee class)", unit: "ea", unitPrice: 215, kind: "material" },
  { trade: "hvac", description: "Programmable thermostat, basic", unit: "ea", unitPrice: 38.5, kind: "material" },
  { trade: "hvac", description: "Flex duct, R8 8 in x 25 ft", unit: "ea", unitPrice: 65, kind: "material" },
  { trade: "hvac", description: "Sheet metal duct, 6 in round per ft", unit: "lf", unitPrice: 4.85, kind: "material" },
  { trade: "hvac", description: "Supply register, 4x10 brushed nickel", unit: "ea", unitPrice: 22.5, kind: "material" },
  { trade: "hvac", description: "Return air grille, 14x20", unit: "ea", unitPrice: 28.5, kind: "material" },
  { trade: "hvac", description: "Furnace install (replacement)", unit: "ea", unitPrice: 1450, kind: "labor" },
  { trade: "hvac", description: "AC install (replacement, with line set)", unit: "ea", unitPrice: 1850, kind: "labor" },
  { trade: "hvac", description: "Mini-split install (head + line set)", unit: "ea", unitPrice: 1250, kind: "labor" },
  { trade: "hvac", description: "Duct run, new 8 in to register", unit: "ea", unitPrice: 285, kind: "labor" },
  { trade: "hvac", description: "Replace thermostat", unit: "ea", unitPrice: 145, kind: "labor" },
]
